USE [Fidelis]
GO

DROP INDEX [IX_SandboxSubmissionStatus2] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_SandboxSubmissionStatus1] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_Type] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_SHA256] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_SHA1] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_SandboxHasMalware] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_ReportingFileName] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_ReportingEndpointName] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_ReportingDate] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_OSType] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_MalwareAlert] ON [dbo].[FileZoo]
GO

DROP INDEX [IX_FileZoo_FileSize] ON [dbo].[FileZoo]
GO

ALTER TABLE [dbo].[FileZoo] DROP CONSTRAINT [PK_FileZoo_MD5] WITH ( ONLINE = OFF )
GO

SET ANSI_PADDING ON
GO

ALTER TABLE [dbo].[FileZoo] ADD  CONSTRAINT [PK_FileZoo_MD5] PRIMARY KEY CLUSTERED
(
	[MD5] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_FileSize] ON [dbo].[FileZoo]
(
	[FileSize] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_MalwareAlert] ON [dbo].[FileZoo]
(
	[SandboxHasMalware] ASC,
	[SandboxAlertGenerated] ASC
)
WHERE ([SandboxHasMalware]=(1) AND [SandboxAlertGenerated]=(0))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_OSType] ON [dbo].[FileZoo]
(
	[OSType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_ReportingDate] ON [dbo].[FileZoo]
(
	[ReportingDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_ReportingEndpointName] ON [dbo].[FileZoo]
(
	[ReportingEndpointName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_ReportingFileName] ON [dbo].[FileZoo]
(
	[ReportingFileName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_SandboxHasMalware] ON [dbo].[FileZoo]
(
	[SandboxHasMalware] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_SHA1] ON [dbo].[FileZoo]
(
	[SHA1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_SHA256] ON [dbo].[FileZoo]
(
	[SHA256] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_FileZoo_Type] ON [dbo].[FileZoo]
(
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_SandboxSubmissionStatus1] ON [dbo].[FileZoo]
(
	[Type] ASC,
	[SandboxSubmissionStatus] ASC,
	[ReportingDate] ASC
)
INCLUDE([MD5],[OSType])
WHERE ([OSType]=(1) AND [Type]=(0) AND [SandboxSubmissionStatus]<=(3))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_SandboxSubmissionStatus2] ON [dbo].[FileZoo]
(
	[Type] ASC,
	[SandboxSubmissionStatus] ASC,
	[ReportingDate] ASC
)
INCLUDE([MD5],[OSType])
WHERE ([OSType] IS NULL AND [Type]=(0) AND [SandboxSubmissionStatus]<=(3))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

